feign:
  okhttp:
    enabled: true
    logging:
      level: ${OKHTTP_LOGGING_LEVEL:BODY}
server:
  port: 8088

log:
  urls:
    - url: /user/get
      status: 200, 500
      request:
        requestBody: true
        header: true
      response:
        responseBody: true
        header: true
    - url: /hello
      status: 200, 500
      request:
        requestBody: true
        header: false
      response:
        responseBody: true
        header: true
